package wizards.global_schema_config;

public enum NodeType {

    DATABASE, DATABASE_URL, DATABASE_MODEL, TABLE, TABLE_INFO, COLUMN, COLUMN_INFO, PRIMARY_KEY, FOREIGN_KEY, GLOBAL_TABLES, GLOBAL_TABLE,
    GLOBAL_COLUMN, MATCHES, TABLE_MATCHES, COLUMN_MATCHES, COLUMN_MATCHES_TYPE
}
