package main_app.wizards.global_schema_config;

import main_app.presto_com.PrestoMediator;

import javax.swing.*;
import javax.swing.text.View;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class ViewCreator extends JFrame {
    private JPanel mainPanel;
    private JTextArea sqlCodeText;
    private JLabel helpLabel;
    private JButton createViewButton;
    private JButton cancelButton;
    private PrestoMediator prestoMediator;
    private String tableName;
    private GlobalSchemaConfiguration globalSchemaConfiguration;

    public ViewCreator(PrestoMediator prestoMediator, GlobalSchemaConfiguration globalSchemaConfiguration, String tableName) {
        this.prestoMediator = prestoMediator;
        this.tableName = tableName;
        this.globalSchemaConfiguration = globalSchemaConfiguration;
        helpLabel.setText("<html><p>This feature is for experienced users.</p>" +
                "<p>Use SQL code to modify the structure of the table and create a view. " +
                "This code will be executed each time data is fetched from this table.</p>" +
                "<p>An example of a view is to write code that unpivots a column(s).</p>" +
                "<p>(Do not use any ';' at the end)</p></html>");

        sqlCodeText.setWrapStyleWord(true);
        sqlCodeText.setLineWrap(true);

        createViewButton.addActionListener(actionEvent -> testAndCreateView());

        cancelButton.addActionListener(actionEvent -> closeWindow());

        this.setPreferredSize(new Dimension(700, 650));
        setContentPane(mainPanel);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setTitle("View creation");
        pack();
        setLocationRelativeTo(null);
        setVisible(true);

    }

    public void testAndCreateView() {
        String sqlCode = sqlCodeText.getText();
        if (sqlCode.isEmpty())
            return;
        //get sql code and execute it once on Presto.
        List<String[]> result = prestoMediator.getQueryColsName(sqlCode + " limit 1");
        if (result == null || result.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error Executing inserted query.", "", JOptionPane.ERROR_MESSAGE);
            globalSchemaConfiguration.setViewInfo(null, "");
            return;
        }
        globalSchemaConfiguration.setViewInfo(result, sqlCode);
        dispose();
    }

    private void closeWindow() {
        this.setVisible(false);
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        final JScrollPane scrollPane1 = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(scrollPane1, gbc);
        sqlCodeText = new JTextArea();
        scrollPane1.setViewportView(sqlCodeText);
        helpLabel = new JLabel();
        helpLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 0.2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(helpLabel, gbc);
        createViewButton = new JButton();
        createViewButton.setText("Create View");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 0.4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(createViewButton, gbc);
        cancelButton = new JButton();
        cancelButton.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 0.4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(cancelButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
